// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"github.com/xu756/appserver/app/admin/internal/logic"
	"github.com/xu756/appserver/app/admin/internal/svc"
	"github.com/xu756/appserver/app/admin/pb"
)

type AdminRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminRpcServer
}

func NewAdminRpcServer(svcCtx *svc.ServiceContext) *AdminRpcServer {
	return &AdminRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminRpcServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.UserInfo, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
