version: '3'
networks:
  env_net:
    external: true

services:
  appserver:
    image: mymodd:latest
    container_name: appserver
    working_dir: /go/appserver
    networks:
      - env_net
    volumes:
      - /code/go/appserver:/go/appserver
