// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package adminrpc

import (
	"context"

	"github.com/xu756/appserver/app/admin/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty          = pb.Empty
	GetUserInfoReq = pb.GetUserInfoReq
	UserInfo       = pb.UserInfo

	AdminRpc interface {
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*UserInfo, error)
	}

	defaultAdminRpc struct {
		cli zrpc.Client
	}
)

func NewAdminRpc(cli zrpc.Client) AdminRpc {
	return &defaultAdminRpc{
		cli: cli,
	}
}

func (m *defaultAdminRpc) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := pb.NewAdminRpcClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
