// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: admin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminRpcClient is the client API for AdminRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminRpcClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*UserInfo, error)
}

type adminRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminRpcClient(cc grpc.ClientConnInterface) AdminRpcClient {
	return &adminRpcClient{cc}
}

func (c *adminRpcClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/pb.adminRpc/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminRpcServer is the server API for AdminRpc service.
// All implementations must embed UnimplementedAdminRpcServer
// for forward compatibility
type AdminRpcServer interface {
	GetUserInfo(context.Context, *GetUserInfoReq) (*UserInfo, error)
	mustEmbedUnimplementedAdminRpcServer()
}

// UnimplementedAdminRpcServer must be embedded to have forward compatible implementations.
type UnimplementedAdminRpcServer struct {
}

func (UnimplementedAdminRpcServer) GetUserInfo(context.Context, *GetUserInfoReq) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedAdminRpcServer) mustEmbedUnimplementedAdminRpcServer() {}

// UnsafeAdminRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminRpcServer will
// result in compilation errors.
type UnsafeAdminRpcServer interface {
	mustEmbedUnimplementedAdminRpcServer()
}

func RegisterAdminRpcServer(s grpc.ServiceRegistrar, srv AdminRpcServer) {
	s.RegisterService(&AdminRpc_ServiceDesc, srv)
}

func _AdminRpc_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.adminRpc/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminRpc_ServiceDesc is the grpc.ServiceDesc for AdminRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.adminRpc",
	HandlerType: (*AdminRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _AdminRpc_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
