// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/xu756/appserver/api/noauth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/captcha",
				Handler: CaptchaCompareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/mobile",
				Handler: LoginByMobileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/auth/:code",
				Handler: MiniAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/password",
				Handler: LoginByPasswordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/appserver/noAuth"),
	)
}
