// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: im.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImRpcClient is the client API for ImRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImRpcClient interface {
	// 元事件 连接 断开 状态更新 解密错误
	Meta(ctx context.Context, in *ImMeta, opts ...grpc.CallOption) (*ImResp, error)
	// 服务端主动推送
	GetImData(ctx context.Context, in *ImData, opts ...grpc.CallOption) (*ImResp, error)
}

type imRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewImRpcClient(cc grpc.ClientConnInterface) ImRpcClient {
	return &imRpcClient{cc}
}

func (c *imRpcClient) Meta(ctx context.Context, in *ImMeta, opts ...grpc.CallOption) (*ImResp, error) {
	out := new(ImResp)
	err := c.cc.Invoke(ctx, "/pb.ImRpc/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imRpcClient) GetImData(ctx context.Context, in *ImData, opts ...grpc.CallOption) (*ImResp, error) {
	out := new(ImResp)
	err := c.cc.Invoke(ctx, "/pb.ImRpc/GetImData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImRpcServer is the server API for ImRpc service.
// All implementations must embed UnimplementedImRpcServer
// for forward compatibility
type ImRpcServer interface {
	// 元事件 连接 断开 状态更新 解密错误
	Meta(context.Context, *ImMeta) (*ImResp, error)
	// 服务端主动推送
	GetImData(context.Context, *ImData) (*ImResp, error)
	mustEmbedUnimplementedImRpcServer()
}

// UnimplementedImRpcServer must be embedded to have forward compatible implementations.
type UnimplementedImRpcServer struct {
}

func (UnimplementedImRpcServer) Meta(context.Context, *ImMeta) (*ImResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meta not implemented")
}
func (UnimplementedImRpcServer) GetImData(context.Context, *ImData) (*ImResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImData not implemented")
}
func (UnimplementedImRpcServer) mustEmbedUnimplementedImRpcServer() {}

// UnsafeImRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImRpcServer will
// result in compilation errors.
type UnsafeImRpcServer interface {
	mustEmbedUnimplementedImRpcServer()
}

func RegisterImRpcServer(s grpc.ServiceRegistrar, srv ImRpcServer) {
	s.RegisterService(&ImRpc_ServiceDesc, srv)
}

func _ImRpc_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImRpcServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ImRpc/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImRpcServer).Meta(ctx, req.(*ImMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImRpc_GetImData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImRpcServer).GetImData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ImRpc/GetImData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImRpcServer).GetImData(ctx, req.(*ImData))
	}
	return interceptor(ctx, in, info, handler)
}

// ImRpc_ServiceDesc is the grpc.ServiceDesc for ImRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ImRpc",
	HandlerType: (*ImRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Meta",
			Handler:    _ImRpc_Meta_Handler,
		},
		{
			MethodName: "GetImData",
			Handler:    _ImRpc_GetImData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im.proto",
}
