// Code generated by goctl. DO NOT EDIT.
// Source: im.proto

package imlogin

import (
	"context"

	"github.com/xu756/appserver/app/im/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ImData = pb.ImData
	ImMeta = pb.ImMeta
	ImResp = pb.ImResp

	ImLogin interface {
		// 元事件 连接 断开 状态更新 解密错误
		Meta(ctx context.Context, in *ImMeta, opts ...grpc.CallOption) (*ImResp, error)
		// 服务端主动推送
		GetImData(ctx context.Context, in *ImData, opts ...grpc.CallOption) (*ImResp, error)
	}

	defaultImLogin struct {
		cli zrpc.Client
	}
)

func NewImLogin(cli zrpc.Client) ImLogin {
	return &defaultImLogin{
		cli: cli,
	}
}

// 元事件 连接 断开 状态更新 解密错误
func (m *defaultImLogin) Meta(ctx context.Context, in *ImMeta, opts ...grpc.CallOption) (*ImResp, error) {
	client := pb.NewImLoginClient(m.cli.Conn())
	return client.Meta(ctx, in, opts...)
}

// 服务端主动推送
func (m *defaultImLogin) GetImData(ctx context.Context, in *ImData, opts ...grpc.CallOption) (*ImResp, error) {
	client := pb.NewImLoginClient(m.cli.Conn())
	return client.GetImData(ctx, in, opts...)
}
