// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/xu756/appserver/api/conn/imserver/internal/svc"
)

func RegisterHandlers(server *http.Server, serverCtx *svc.ServiceContext) {
	// 设置路由、中间件、处理新连接的函数
	mux := http.NewServeMux()

	//mux.HandleFunc("/websocket", addConn(serverCtx))
	server.Handler = mux
}
