addr:
  adminApiAddr: 0.0.0.0:7080
  userRpcAddr: 0.0.0.0:8081
rpc:
  userRpcAddr: 0.0.0.0:8081
dbConfig:
  dbType: postgres
  addr: 127.0.0.1
  port: 5432
  username: root
  password: fyU0bj2KLndYN6CKYubb
  dbName: appServer
redisConfig:
  addr: 127.0.0.1:6379
  password: Y5dg5tg8050oigInC30sf
  db: 2
jwtConfig:
  signKey: Tqede8rNvZvbKmjqYpQRvwLxsGR
  expire: 36000
emailConfig:
  smtpAddr: smtp.feishu.cn:587
  password: smcfUO20MyiAEijy
  from: grade@xynu.email
  host: smtp.feishu.cn
mqUrl : amqp://root:Vmjsim4D@localhost:5672/
