// Code generated by goctl. DO NOT EDIT.
// Source: im.proto

package server

import (
	"context"

	"github.com/xu756/appserver/app/im/internal/logic"
	"github.com/xu756/appserver/app/im/internal/svc"
	"github.com/xu756/appserver/app/im/pb"
)

type ImLoginServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImLoginServer
}

func NewImLoginServer(svcCtx *svc.ServiceContext) *ImLoginServer {
	return &ImLoginServer{
		svcCtx: svcCtx,
	}
}

// 元事件 连接 断开 状态更新 解密错误
func (s *ImLoginServer) Meta(ctx context.Context, in *pb.ImMeta) (*pb.ImResp, error) {
	l := logic.NewMetaLogic(ctx, s.svcCtx)
	return l.Meta(in)
}

// 服务端主动推送
func (s *ImLoginServer) GetImData(ctx context.Context, in *pb.ImData) (*pb.ImResp, error) {
	l := logic.NewGetImDataLogic(ctx, s.svcCtx)
	return l.GetImData(in)
}
