// Code generated by goctl. DO NOT EDIT.
// Source: login.proto

package server

import (
	"context"

	"github.com/xu756/appserver/app/login/internal/logic"
	"github.com/xu756/appserver/app/login/internal/svc"
	"github.com/xu756/appserver/app/login/pb"
)

type LoginRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLoginRpcServer
}

func NewLoginRpcServer(svcCtx *svc.ServiceContext) *LoginRpcServer {
	return &LoginRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginRpcServer) MiniLoginByMobile(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewMiniLoginByMobileLogic(ctx, s.svcCtx)
	return l.MiniLoginByMobile(in)
}

func (s *LoginRpcServer) MiniLoginByAuth(ctx context.Context, in *pb.MiniAuthReq) (*pb.LoginResp, error) {
	l := logic.NewMiniLoginByAuthLogic(ctx, s.svcCtx)
	return l.MiniLoginByAuth(in)
}

func (s *LoginRpcServer) GetCaptcha(ctx context.Context, in *pb.Empty) (*pb.CaptchaResp, error) {
	l := logic.NewGetCaptchaLogic(ctx, s.svcCtx)
	return l.GetCaptcha(in)
}

func (s *LoginRpcServer) CaptchaCompare(ctx context.Context, in *pb.CaptchaCheckReq) (*pb.CaptchaCheckResp, error) {
	l := logic.NewCaptchaCompareLogic(ctx, s.svcCtx)
	return l.CaptchaCompare(in)
}
